name:                NoviSteps3Q
version:             0.0.0
github:              nobsun/NoviSteps3Q
license:             BSD3
author:              Nobuo Yamashita
maintainer:          nobsun@sampou.org
copyright:           © 2024, Nobuo Yamashita

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/NoviSteps3Q#readme>

dependencies:
- base >= 4.7 && < 5
- utf8-string
- unicode-show
- hspec
- main-tester
- Cabal
- Cabal-syntax
- QuickCheck
- adjunctions
- array
- attoparsec
- bifunctors
- binary
- bitvec
- bytestring
- comonad
- containers
- contravariant
- deepseq
- directory
- distributive
- exceptions
- extra
- fgl
- filepath
- free
- ghc-bignum
- ghc-boot-th
- ghc-prim
- hashable
- heaps
- indexed-traversable
- indexed-traversable-instances
- integer-gmp
- integer-logarithms
- kan-extensions
- lens
- linear-base
- list-t
- massiv
- megaparsec
- mono-traversable
- mtl
- mutable-containers
- mwc-random
- parallel
- parsec
- parser-combinators
- pretty
- primitive
- process
- profunctors
- psqueues
- random
- reflection
- regex-tdfa
- safe-exceptions
- scientific
- semialign
- semigroupoids
- split
- stm
- strict
- strict-lens
- tagged
- template-haskell
- text
- tf-random
- these
- these-lens
- time
- transformers
- trifecta
- unboxing-vector
- unix
- unordered-containers
- utility-ht
- vector
- vector-algorithms
- vector-stream
- vector-th-unbox
- xhtml

language: GHC2021

default-extensions:
- ImplicitParams
- ImportQualifiedPost
- LambdaCase
- LexicalNegation
- MultiWayIf
- NPlusKPatterns
- OverloadedStrings
- DataKinds
- PolyKinds
- NoStarIsType
- TypeFamilyDependencies
- UndecidableInstances

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-orphans

library:
  source-dirs: src

executables:
  abc384c:
    main:               Main.hs
    source-dirs:        app/abc384c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc190c:
    main:               Main.hs
    source-dirs:        app/abc190c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc167c:
    main:               Main.hs
    source-dirs:        app/abc167c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc128c:
    main:               Main.hs
    source-dirs:        app/abc128c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc114c:
    main:               Main.hs
    source-dirs:        app/abc114c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc260c:
    main:               Main.hs
    source-dirs:        app/abc260c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc247d:
    main:               Main.hs
    source-dirs:        app/abc247d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc389c:
    main:               Main.hs
    source-dirs:        app/abc389c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc391c:
    main:               Main.hs
    source-dirs:        app/abc391c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc269c:
    main:               Main.hs
    source-dirs:        app/abc269c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc289c:
    main:               Main.hs
    source-dirs:        app/abc289c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc358c:
    main:               Main.hs
    source-dirs:        app/abc358c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc374c:
    main:               Main.hs
    source-dirs:        app/abc374c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc283d:
    main:               Main.hs
    source-dirs:        app/abc283d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc307d:
    main:               Main.hs
    source-dirs:        app/abc307d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc240d:
    main:               Main.hs
    source-dirs:        app/abc240d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc259c:
    main:               Main.hs
    source-dirs:        app/abc259c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc070d:
    main:               Main.hs
    source-dirs:        app/abc070d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc062c:
    main:               Main.hs
    source-dirs:        app/abc062c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc054c:
    main:               Main.hs
    source-dirs:        app/abc054c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc053d:
    main:               Main.hs
    source-dirs:        app/abc053d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc052c:
    main:               Main.hs
    source-dirs:        app/abc052c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc052d:
    main:               Main.hs
    source-dirs:        app/abc052d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc050c:
    main:               Main.hs
    source-dirs:        app/abc050c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc046d:
    main:               Main.hs
    source-dirs:        app/abc046d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc015c:
    main:               Main.hs
    source-dirs:        app/abc015c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc007c:
    main:               Main.hs
    source-dirs:        app/abc007c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc005c:
    main:               Main.hs
    source-dirs:        app/abc005c
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  abc002d:
    main:               Main.hs
    source-dirs:        app/abc002d
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  encyclopediaofparentheses:
    main:               Main.hs
    source-dirs:        app/encyclopediaofparentheses
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  vacation:
    main:               Main.hs
    source-dirs:        app/vacation
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  nextletter:
    main:               Main.hs
    source-dirs:        app/nextletter
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  alds1_3_a:
    main:               Main.hs
    source-dirs:        app/alds1_3_a
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  alds1_3_b:
    main:               Main.hs
    source-dirs:        app/alds1_3_b
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  knapsack1:
    main:               Main.hs
    source-dirs:        app/knapsack1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  grid1:
    main:               Main.hs
    source-dirs:        app/grid1
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  past202012openf:
    main:               Main.hs
    source-dirs:        app/past202012openf
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aclpracticea:
    main:               Main.hs
    source-dirs:        app/aclpracticea
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  joig2021openc:
    main:               Main.hs
    source-dirs:        app/joig2021openc
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  joi2007yof:
    main:               Main.hs
    source-dirs:        app/joi2007yof
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua13:
    main:               Main.hs
    source-dirs:        app/tessokua13
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua15:
    main:               Main.hs
    source-dirs:        app/tessokua15
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua41:
    main:               Main.hs
    source-dirs:        app/tessokua41
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua43:
    main:               Main.hs
    source-dirs:        app/tessokua43
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua55:
    main:               Main.hs
    source-dirs:        app/tessokua55
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokua66:
    main:               Main.hs
    source-dirs:        app/tessokua66
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokub13:
    main:               Main.hs
    source-dirs:        app/tessokub13
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokub40:
    main:               Main.hs
    source-dirs:        app/tessokub40
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokub44:
    main:               Main.hs
    source-dirs:        app/tessokub44
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokub51:
    main:               Main.hs
    source-dirs:        app/tessokub51
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokuc05:
    main:               Main.hs
    source-dirs:        app/tessokuc05
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  tessokuc07:
    main:               Main.hs
    source-dirs:        app/tessokuc07
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam009:
    main:               Main.hs
    source-dirs:        app/aam009
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam018:
    main:               Main.hs
    source-dirs:        app/aam018
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam022:
    main:               Main.hs
    source-dirs:        app/aam022
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam023:
    main:               Main.hs
    source-dirs:        app/aam023
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam024:
    main:               Main.hs
    source-dirs:        app/aam024
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam025:
    main:               Main.hs
    source-dirs:        app/aam025
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam026:
    main:               Main.hs
    source-dirs:        app/aam026
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam027:
    main:               Main.hs
    source-dirs:        app/aam027
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam031:
    main:               Main.hs
    source-dirs:        app/aam031
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam033:
    main:               Main.hs
    source-dirs:        app/aam033
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  agc012a:
    main:               Main.hs
    source-dirs:        app/agc012a
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  agc011a:
    main:               Main.hs
    source-dirs:        app/agc011a
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam037:
    main:               Main.hs
    source-dirs:        app/aam037
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam039:
    main:               Main.hs
    source-dirs:        app/aam039
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam041:
    main:               Main.hs
    source-dirs:        app/aam041
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam043:
    main:               Main.hs
    source-dirs:        app/aam043
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam044:
    main:               Main.hs
    source-dirs:        app/aam044
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  aam050:
    main:               Main.hs
    source-dirs:        app/aam050
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  amm063:
    main:               Main.hs
    source-dirs:        app/amm063
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  agc009_a:
    main:               Main.hs
    source-dirs:        app/agc009_a
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  hsi:
    main:               Main.hs
    source-dirs:        app/hsi
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  4qfibonaccieasy:
    main:               Main.hs
    source-dirs:        app/4qfibonaccieasy
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  4qa16:
    main:               Main.hs
    source-dirs:        app/4qa16
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  4qsunukethecookiepicker:
    main:               Main.hs
    source-dirs:        app/4qsunukethecookiepicker
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  4qsiepinskicarpet:
    main:               Main.hs
    source-dirs:        app/4qsiepinskicarpet
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  6qnutrients:
    main:               Main.hs
    source-dirs:        app/6qnutrients
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  6qpiano2:
    main:               Main.hs
    source-dirs:        app/6qpiano2
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  7qsanitizehands:
    main:               Main.hs
    source-dirs:        app/7qsanitizehands
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  7quppercaseandlowercase:
    main:               Main.hs
    source-dirs:        app/7quppercaseandlowercase
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  manyreplacement:
    main:            Main.hs
    source-dirs:     app/manyreplacement
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  diversityofscores:
    main:            Main.hs
    source-dirs:     app/diversityofscores
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  onetimeswap:
    main:            Main.hs
    source-dirs:     app/onetimeswap
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  sort:
    main:            Main.hs
    source-dirs:     app/sort
    ghc-options:
    - -rtsopts
    dependencies:
    - NoviSteps3Q

  NoviSteps3Q:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - NoviSteps3Q

tests:
  NoviSteps3Q-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - NoviSteps3Q
    - hspec
    - main-tester

  NoviSteps3Q-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - NoviSteps3Q
    - doctest
